name: Deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - main # 해당 브랜치의 푸쉬가 일어날 때 CI/CD를 진행하겠다는 뜻

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: match-bucket-for-deploy
  AWS_S3_BUCKET_DIR: match-client-deploy
  AWS_CODE_DEPLOY_APPLICATION: match-application
  AWS_CODE_DEPLOY_GROUP: match-client-group

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile

      - name: Build # React Build
        run: yarn build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          CI: ""

      - name: zip create
        # zip 파일을 만듭니다(파일명은 자유, 대신 아래 workflow에 적을 파일명과 동일하게 맞춰주세요).
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ${{ env.AWS_REGION }} ./$GITHUB_SHA.zip s3://$AWS_S3_BUCKET/$AWS_S3_BUCKET_DIR/$GITHUB_SHA.zip

      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }}
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }}
          --s3-location bucket=$AWS_S3_BUCKET,key=$AWS_S3_BUCKET_DIR/$GITHUB_SHA.zip,bundleType=zip
